[package]
name = "tex-fmt"
version = "0.4.6"
authors = ["William George Underwood"]
license = "MIT"
repository = "https://github.com/WGUNDERWOOD/tex-fmt"
edition = "2021"
description = "LaTeX formatter written in Rust"
keywords = ["latex", "formatter"]
categories = ["command-line-utilities", "development-tools"]
exclude = ["tests/*", "extra/*", "*.nix", ".github/*"]

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
regex = "1.11.0"
similar = "2.6.0"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"

[profile.release]
codegen-units = 1
lto = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs"
